// apps/vue-app/dashboard/src/App.vue
<script lang="ts">

// import * as stylex from '@stylexjs/stylex';

// const components = stylex.create({
//   root: {
//     color: 'red',
//     fontSize: '18px',
//     fontWeight: 'bold'
//   }
// });

</script>

<script setup lang="ts">
import ThemeProvider from 'packages/vue/src/system/theme-provider.vue';
import Button from 'packages/vue/src/components/button/src/index.vue';
import Select from 'packages/vue/src/components/select/src/index.vue';
import Form, { type FormItem } from 'packages/vue/src/components/form/src/index.vue';

import { getTheme } from 'packages/common/theme';
import { themeConfig } from './theme/config';

const { theme, themeVariant } = getTheme();

const items: FormItem[] = [
  {
    name: 'firstName',
    label: 'First Name',
    placeholder: 'Enter your first name',
    type: 'text'
  },
  {
    name: 'lastName',
    label: 'Last Name',
    placeholder: 'Enter your last name',
    type: 'text'
  },
  {
    name: 'email',
    label: 'Email',
    placeholder: 'Enter your email address',
    // type: 'email'
  },
  {
    name: 'password',
    label: 'Password',
    placeholder: 'Enter your password',
    type: 'password'
  }
]

const handleFormSubmit = (formData: any) => {
  console.log('Form submitted with data:', formData);
  // alert('Form submitted successfully!');
}
</script>

<template>
  <ThemeProvider :theme="theme" :theme-config="themeConfig" :theme-variant="themeVariant">
    <Button>Button</Button>
    <ThemeProvider>
      <Button size="lg">Button</Button>
      <Select>Select</Select>
      <Form
          :items="items"
          @submit="handleFormSubmit"
      />
    </ThemeProvider>
  </ThemeProvider>
</template>

// apps/website/src/App.tsx
import React from 'react';
import type { FC, ReactNode } from 'react';
import * as stylex from '@stylexjs/stylex';
import Button, { ButtonKeys } from '@packages/react/components/button';
import Select, { SelectKeys } from '@packages/react/components/select';
import { ThemeProvider } from '@packages/react/hooks/use-theme';
import type { StylesDefinitions } from '@packages/react/hooks/use-theme';
import { getTheme, darkTheme } from 'packages/common/theme';
import { themeConfig } from './theme/config';

interface AppProps {
  children: ReactNode
}

const buttonStyles = stylex.create({
  root: {
    // position: 'fixed',
    backgroundColor: 'pink'
  }
} as Partial<Pick<StylesDefinitions, ButtonKeys>>);

const selectStyles = stylex.create({
  root: {
    paddingInline: '10px'
  },
  label: {
    color: 'pink'
  }
} as Partial<Pick<StylesDefinitions, SelectKeys>>);

const App: FC<AppProps> = ({
  children
}) => {
  const { theme, themeVariant } = getTheme();

  console.log('theme', theme)

  return (
    <ThemeProvider
      // theme={theme}
      themeVariant={themeVariant}
      themeConfig={{
        globalProps: {
          mode: 'dark',
          platform: 'desktop'
        },
        ...themeConfig
      }}
    >
      <Button>
        Button default
      </Button>
      <Button
        color="primary"
        size="lg"
        type="ghost"
        styles={buttonStyles}
      >
        Button 1
      </Button>
      <ThemeProvider
        theme={darkTheme}
        themeConfig={{
          globalProps: {
            platform: 'mobile'
          },
          test: '123'
        }}
      >
        <Button
          color="primary"
          // size="lg"
          type="ghost"
        >
          Button 2
        </Button>
        <Select
          options={{
            items: [
              {
                label: 'React',
                value: 'react'
              },
              {
                label: 'Vue',
                value: 'vue'
              }
            ]
          }}
          styles={selectStyles}
        >
          Test
        </Select>
      </ThemeProvider>
      {children}
    </ThemeProvider>
  )
}

export default App
